default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # This must match what POSTGRES_USER was set to in docker-compose.yml.
  username: panda

  # This must be 127.0.0.1 and not localhost.
  host: 127.0.0.1
  port: 5434

development:
  <<: *default
  database: panda_development

test:
  <<: *default
  database: panda_test

production:
  <<: *default
  database: panda_production
  username: panda
  password: <%= ENV['DB_PASSWORD'] %>
